###一、顺序结构
#程序从上到下顺序地执行代码，中间没有任何判断和跳转，直接到程序结束
'''把大象症状进冰箱一共需要几步？'''
print('----程序开始----')
print('---打开冰箱门---')
print('---把大象塞进冰箱---')
print('---关上冰箱门---')

###对象的布尔值
#python一切皆对象，所有对象都有一个布尔值
#获取对象的布尔值；使用内置函数bool()
'''测试对象的布尔值'''
print(bool(False))#F
print(bool(0))#F
print(bool(0.0))#F
print(bool(None))#F
print(bool(''))#f
print(bool(""))#F
print(bool([]))#空列表
print(bool(list()))#空列表
print(bool(()))#空元组
print(bool(tuple()))#空元组
print(bool({}))#空字典
print(bool(dict()))#空字典
print(bool(set()))#空集合
print('以上对象外的布尔值均为false')
print('-------------------其他对象的布尔值均为true----------------------')